# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-05 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('comment', models.TextField(max_length=1500)),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
