# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-04 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20190822_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=1500),
        ),
    ]
