# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-22 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=254)),
                ('summary', models.TextField()),
                ('ticket_type', models.CharField(max_length=30)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='images')),
                ('upvotes', models.IntegerField(default=0)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creator', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(default='Backlog', max_length=30)),
                ('initiation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
