# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-28 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='Backlog', max_length=30),
        ),
    ]