# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-28 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20190628_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='ticket',
            name='creator',
            field=models.CharField(default='admin', max_length=254),
            preserve_default=False,
        ),
    ]