# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-28 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20190628_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]